rvm:
  - 2.1.1

bundler_args: --without development

language: node_js

node_js:
  - 0.10

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - npm install -g grunt-cli

#after_success:
#  - grunt build
#  - chmod +x deploy.sh
#  - ./deploy.sh

#env:
#  global:
#    secure: <http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables>
